### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by Zanatoos** [rvantonder/ttwe-proto#1]
Hello, 
I'm actually trying to learn how i could do a man in the middle attack and i got the facedancers for this. 
Then i saw the ttwe proto who seemed quite useful so i tried to use it wiring a mouse to a facedancer21 to my pc and another pc to another facedancer21 to my pc. And after configuring, i launched the TTWE_host.py, then the TTWE_client and i get this error message : 

`$ sudo python3 client/TTWEClient.py -v

Facedancer reset
GoodFET monitor initialized
MAXUSB initialized
MAXUSB enabled
MAXUSB revision 19
Attempting connection
MAXUSB connected device TTWEClient Device
Done connecting
Traceback (most recent call last):
  File "client/TTWEClient.py", line 281, in <module>
    u.service_irqs()
  File "/home/Zanatos/Documents/ttwe-proto/client/MAXUSBApp.py", line 227, in service_irqs
    self.connected_device.before_handle()
  File "client/TTWEClient.py", line 105, in before_handle
    self.write_ep0_snd.flush()
BrokenPipeError: [Errno 32] Broken pipe
`

After few tests, i was wondering if the problem were due to versions of the software like pyserial. Could you tell me which version you used, or which versions work right now,

Thanks

**Comment by rvantonder** [comment]
Hi. It's been a long time since I ran my own code. Not sure which version was used. However, I remember getting `Broken pipe` if you plugged or started the clients in the wrong order. Since you seem to correctly be adding the host one first, it might be useful to check that the facedancers are being registered on the right interface (e.g., `ttyUSB0` for host).

Edit: I had a quick look at the code, and it's possible the devices are being registered the other way around (`ttyUSB0` assigned to client). I recommend trying adding them in different orders (client first and then host, and other way around).

**Comment by Zanatoos** [comment]
Hi ! Thanks for your quick answer !
So, when i thought it was a version issue i looked into the previous commit of Goodfet by TravisGoodSpeed and i saw he changed the Goodfet.py because PySerial doesnt support the setTimeout so he replaced occurrences of 'self.serialport.setTimeout();' by 'self.serialport.timeout=;' and after changing that with launching the client first it seems to work a lot better. 
But, it gets stuck there (cf attachments) and it doesn't do anything more. So i put input in the code to see where it's stuck and it is at this line : 'self.rcv = self.read_ep0_snd.readline()' in before_handle function in TTWEHost.py around the line 55. 

[http://zupimages.net/viewer.php?id=17/11/5u6g.png](url)
[http://zupimages.net/viewer.php?id=17/11/419c.png](url)

EDIT : After some searching it seems it might be due to some versions issues of the firmware of the facedancer. So do you still have the facedancer21.hex to compare if it's the same one that i'm using ?
EDIT2: After trying to  understand the problem, it seems TTWEHost is waiting to read something from the pipe ep0_snd which should be written by TTWEClient i guess but i don't see what it is expecting.
I also noticed that my mouse is powered up when i plug it in, but after one sec it shuts down during 
'Bus will now reset'
'Bus done resetting' 
And after printing all the variables that are written into the pipes, i saw that all of it were empty :/
